"""核心常量模块。

本文件属于 `app/core` 基础能力层，负责保存 02 阶段允许的通用常量。
本文件不负责策略参数、交易参数、外部请求、数据库读写、Redis 读写、
Hermes 发送、DeepSeek 调用或任何交易执行能力。
主要被 `app/core/config.py`、测试和后续基础模块调用。
"""

from __future__ import annotations

APP_ENV_DEV = "dev"
APP_ENV_TEST = "test"
APP_ENV_PROD = "prod"

DEFAULT_APP_NAME = "hermes_btc_agent"
DEFAULT_LOG_LEVEL = "INFO"
DEFAULT_TIMEZONE = "UTC"
DEFAULT_SYMBOL = "BTCUSDT"
DEFAULT_INTERVAL = "4h"

DEFAULT_MYSQL_PORT = 3306
DEFAULT_MYSQL_CHARSET = "utf8mb4"
DEFAULT_MYSQL_POOL_SIZE = 5
DEFAULT_MYSQL_MAX_OVERFLOW = 10
DEFAULT_MYSQL_POOL_RECYCLE = 3600
DEFAULT_MYSQL_POOL_PRE_PING = True

DEFAULT_REDIS_PORT = 6379
DEFAULT_REDIS_DB = 0
DEFAULT_REDIS_SOCKET_TIMEOUT = 5.0
DEFAULT_REDIS_DECODE_RESPONSES = True

DEFAULT_BINANCE_BASE_URL = "https://fapi.binance.com"
DEFAULT_BINANCE_WS_BASE_URL = "wss://fstream.binance.com/market/ws"
DEFAULT_BINANCE_TIMEOUT_SECONDS = 10.0
DEFAULT_BINANCE_MAX_RETRIES = 2
DEFAULT_BINANCE_RETRY_BACKOFF_SECONDS = 1.0
DEFAULT_BINANCE_KLINE_DEFAULT_LIMIT = 10
DEFAULT_BINANCE_KLINE_MAX_LIMIT = 1500

DEFAULT_PRICE_MONITOR_SYMBOL = "BTCUSDT"
DEFAULT_PRICE_MONITOR_WS_STREAM = "aggTrade"
DEFAULT_PRICE_MONITOR_INTERVAL_SECONDS = 10
DEFAULT_PRICE_MONITOR_CHANGE_THRESHOLD = "0.01"
DEFAULT_PRICE_MONITOR_REDIS_KEY = "bitcoin_price"
DEFAULT_PRICE_MONITOR_REDIS_TTL_SECONDS = 120
DEFAULT_PRICE_MONITOR_ALERT_COOLDOWN_SECONDS = 60
DEFAULT_PRICE_MONITOR_ENABLE_PRICE_ALERTS = True
DEFAULT_PRICE_MONITOR_WS_RECONNECT_MIN_SECONDS = 1.0
DEFAULT_PRICE_MONITOR_WS_RECONNECT_MAX_SECONDS = 60.0
DEFAULT_PRICE_MONITOR_NO_EVENT_TIMEOUT_SECONDS = 30

DEFAULT_SCHEDULER_ENABLED = True
DEFAULT_SCHEDULER_POLL_INTERVAL_SECONDS = 30
DEFAULT_SCHEDULER_RUNNING_LOCK_TTL_SECONDS = 1800
DEFAULT_SCHEDULER_COMPLETED_MARKER_TTL_SECONDS = 259200
DEFAULT_SCHEDULER_STATUS_MARKER_TTL_SECONDS = 86400
DEFAULT_SCHEDULER_SLOT_LOG_COOLDOWN_SECONDS = 300

DEFAULT_KLINE_4H_INCREMENTAL_COLLECT_ENABLED = True
DEFAULT_KLINE_4H_INCREMENTAL_COLLECT_SYMBOL = "BTCUSDT"
DEFAULT_KLINE_4H_INCREMENTAL_COLLECT_INTERVAL = "4h"
DEFAULT_KLINE_4H_INCREMENTAL_COLLECT_LIMIT = 6
DEFAULT_KLINE_4H_INCREMENTAL_COLLECT_UTC_MINUTES_AFTER_CLOSE = 5

DEFAULT_KLINE_1D_INCREMENTAL_COLLECT_ENABLED = True
DEFAULT_KLINE_1D_INCREMENTAL_COLLECT_SYMBOL = "BTCUSDT"
DEFAULT_KLINE_1D_INCREMENTAL_COLLECT_INTERVAL = "1d"
DEFAULT_KLINE_1D_INCREMENTAL_COLLECT_MAX_CLOSED_COUNT = 30
DEFAULT_KLINE_1D_INCREMENTAL_COLLECT_LOCK_TTL_SECONDS = 300
DEFAULT_KLINE_1D_INCREMENTAL_COLLECT_UTC_TIME = "00:10"

DEFAULT_DAILY_KLINE_INTEGRITY_ENABLED = True
DEFAULT_DAILY_KLINE_INTEGRITY_SYMBOL = "BTCUSDT"
DEFAULT_DAILY_KLINE_INTEGRITY_INTERVAL = "4h"
DEFAULT_DAILY_KLINE_INTEGRITY_LIMIT = 100
DEFAULT_DAILY_KLINE_INTEGRITY_NOTIFY_SUCCESS = True
DEFAULT_DAILY_KLINE_INTEGRITY_LOCK_TTL_SECONDS = 1800
DEFAULT_DAILY_KLINE_INTEGRITY_UTC_TIME = "00:30"

DEFAULT_DAILY_KLINE_1D_INTEGRITY_ENABLED = True
DEFAULT_DAILY_KLINE_1D_INTEGRITY_SYMBOL = "BTCUSDT"
DEFAULT_DAILY_KLINE_1D_INTEGRITY_INTERVAL = "1d"
DEFAULT_DAILY_KLINE_1D_INTEGRITY_LIMIT = 500
DEFAULT_DAILY_KLINE_1D_INTEGRITY_NOTIFY_SUCCESS = True
DEFAULT_DAILY_KLINE_1D_INTEGRITY_LOCK_TTL_SECONDS = 1800
DEFAULT_DAILY_KLINE_1D_INTEGRITY_UTC_TIME = "00:20"

DEFAULT_MARKET_CONTEXT_SYMBOL = "BTCUSDT"
DEFAULT_MARKET_CONTEXT_BASE_INTERVAL = "4h"
DEFAULT_MARKET_CONTEXT_HIGHER_INTERVAL = "1d"
DEFAULT_MARKET_CONTEXT_4H_LOOKBACK_COUNT = 180
DEFAULT_MARKET_CONTEXT_1D_LOOKBACK_COUNT = 365

DEFAULT_STRATEGY_SIGNAL_SCHEDULER_ENABLED = False
DEFAULT_STRATEGY_SIGNAL_SYMBOL = "BTCUSDT"
DEFAULT_STRATEGY_SIGNAL_BASE_INTERVAL = "4h"
DEFAULT_STRATEGY_SIGNAL_HIGHER_INTERVAL = "1d"
DEFAULT_STRATEGY_SIGNAL_HERMES_ENABLED = False
DEFAULT_STRATEGY_SIGNAL_HERMES_NOTIFY_SUCCESS = True
DEFAULT_STRATEGY_SIGNAL_HERMES_NOTIFY_PARTIAL_SUCCESS = True
DEFAULT_STRATEGY_SIGNAL_HERMES_NOTIFY_BLOCKED = True
DEFAULT_STRATEGY_SIGNAL_HERMES_NOTIFY_FAILED = True
DEFAULT_STRATEGY_SIGNAL_HERMES_NOTIFY_SKIPPED = False
DEFAULT_STRATEGY_SIGNAL_SCHEDULER_RUNNING_TIMEOUT_SECONDS = 900

DEFAULT_STRATEGY_AGGREGATION_AUTO_RUN_ENABLED = False
DEFAULT_STRATEGY_AGGREGATION_HERMES_ENABLED = False
DEFAULT_STRATEGY_AGGREGATION_HERMES_NOTIFY_SUCCESS = True
DEFAULT_STRATEGY_AGGREGATION_HERMES_NOTIFY_PARTIAL_SUCCESS = True
DEFAULT_STRATEGY_AGGREGATION_HERMES_NOTIFY_BLOCKED = True
DEFAULT_STRATEGY_AGGREGATION_HERMES_NOTIFY_FAILED = True
DEFAULT_STRATEGY_AGGREGATION_HERMES_NOTIFY_SKIPPED = False

DEFAULT_STRATEGY_ADVICE_SCHEDULER_ENABLED = False
DEFAULT_STRATEGY_ADVICE_NOTIFICATION_SEND_ENABLED = False

DEFAULT_MANUAL_EXECUTION_FEE_RATE = "0.0002"
DEFAULT_MANUAL_EXECUTION_RECEIPT_SEND_ENABLED = False
DEFAULT_MANUAL_EXECUTION_HERMES_ENTRY_ENABLED = False
DEFAULT_MANUAL_EXECUTION_HERMES_REPLY_SEND_ENABLED = False
DEFAULT_MANUAL_EXECUTION_INTENT_EXPIRE_MINUTES = 10

DEFAULT_MODEL_REVIEW_ENABLED = False
DEFAULT_MODEL_REVIEW_DRY_RUN = True
DEFAULT_MODEL_REVIEW_PROVIDER = "mock"
DEFAULT_MODEL_REVIEW_CONFIG_DIR = "configs/model_review"
DEFAULT_MODEL_REVIEW_MAX_INPUT_CHARS = 10000
DEFAULT_MODEL_REVIEW_MAX_OUTPUT_CHARS = 10000
DEFAULT_MODEL_REVIEW_MAX_INPUT_BYTES = 32768
DEFAULT_MODEL_REVIEW_MAX_OUTPUT_BYTES = 32768
DEFAULT_MODEL_REVIEW_MAX_STRATEGY_ITEMS = 30
DEFAULT_MODEL_REVIEW_MAX_REASON_ITEMS_PER_STRATEGY = 5
DEFAULT_MODEL_REVIEW_HERMES_ENABLED = False
DEFAULT_MODEL_REVIEW_PROMPT_TEMPLATE_VERSION = "review_gate_v1"
DEFAULT_MODEL_REVIEW_SCHEMA_VERSION = "review_schema_v1"
DEFAULT_MODEL_REVIEW_REAL_MODEL_ENABLED = False
DEFAULT_MODEL_REVIEW_AUTO_RUN_ENABLED = False
DEFAULT_MODEL_REVIEW_SCHEDULER_ENABLED = False
DEFAULT_MODEL_REVIEW_SCHEDULER_ALLOWED_MODEL_KEYS = ""
DEFAULT_MODEL_REVIEW_DAILY_BUDGET_USD = "0"
DEFAULT_MODEL_REVIEW_MAX_RUNS_PER_4H = 2
DEFAULT_MODEL_REVIEW_REUSE_MAX_BASE_BARS = 3
DEFAULT_MODEL_REVIEW_STEP_RUNNING_TIMEOUT_SECONDS = 300
DEFAULT_MODEL_REVIEW_ARTIFACT_DIR = "runtime/model_review_artifacts"
DEFAULT_MODEL_REVIEW_CAPTURE_RAW_REQUEST = False
DEFAULT_MODEL_REVIEW_CAPTURE_RAW_RESPONSE = False
DEFAULT_MODEL_REVIEW_HERMES_ON_OVERSIZED_OUTPUT = True
DEFAULT_MODEL_REVIEW_RAW_ARTIFACT_MAX_BYTES = 1048576

DEFAULT_HERMES_TIMEOUT_SECONDS = 10.0
DEFAULT_HERMES_MAX_RETRIES = 2
DEFAULT_HERMES_ENABLED = False
DEFAULT_HERMES_DRY_RUN = True

LOG_DIR_NAME = "logs"
DEFAULT_LOG_FILE_NAME = "app.log"

SENSITIVE_FIELD_NAMES = frozenset(
    {
        "mysql_password",
        "redis_password",
        "hermes_webhook_url",
        "hermes_secret",
        "deepseek_api_key",
    }
)

SENSITIVE_TEXT_MARKERS = (
    "password",
    "secret",
    "token",
    "webhook",
    "authorization",
    "cookie",
)
