"""核心常量模块。

本文件属于 `app/core` 基础能力层，负责保存 02 阶段允许的通用常量。
本文件不负责策略参数、交易参数、外部请求、数据库读写、Redis 读写、
Hermes 发送、DeepSeek 调用或任何交易执行能力。
主要被 `app/core/config.py`、测试和后续基础模块调用。
"""

from __future__ import annotations

APP_ENV_DEV = "dev"
APP_ENV_TEST = "test"
APP_ENV_PROD = "prod"

DEFAULT_APP_NAME = "hermes_btc_agent"
DEFAULT_LOG_LEVEL = "INFO"
DEFAULT_TIMEZONE = "UTC"
DEFAULT_SYMBOL = "BTCUSDT"
DEFAULT_INTERVAL = "4h"

DEFAULT_MYSQL_PORT = 3306
DEFAULT_MYSQL_CHARSET = "utf8mb4"
DEFAULT_MYSQL_POOL_SIZE = 5
DEFAULT_MYSQL_MAX_OVERFLOW = 10
DEFAULT_MYSQL_POOL_RECYCLE = 3600
DEFAULT_MYSQL_POOL_PRE_PING = True

DEFAULT_REDIS_PORT = 6379
DEFAULT_REDIS_DB = 0
DEFAULT_REDIS_SOCKET_TIMEOUT = 5.0
DEFAULT_REDIS_DECODE_RESPONSES = True

DEFAULT_BINANCE_BASE_URL = "https://fapi.binance.com"
DEFAULT_BINANCE_WS_BASE_URL = "wss://fstream.binance.com/market/ws"
DEFAULT_BINANCE_TIMEOUT_SECONDS = 10.0
DEFAULT_BINANCE_MAX_RETRIES = 2
DEFAULT_BINANCE_RETRY_BACKOFF_SECONDS = 1.0
DEFAULT_BINANCE_KLINE_DEFAULT_LIMIT = 10
DEFAULT_BINANCE_KLINE_MAX_LIMIT = 1500

DEFAULT_PRICE_MONITOR_SYMBOL = "BTCUSDT"
DEFAULT_PRICE_MONITOR_WS_STREAM = "aggTrade"
DEFAULT_PRICE_MONITOR_INTERVAL_SECONDS = 10
DEFAULT_PRICE_MONITOR_CHANGE_THRESHOLD = "0.01"
DEFAULT_PRICE_MONITOR_REDIS_KEY = "bitcoin_price"
DEFAULT_PRICE_MONITOR_REDIS_TTL_SECONDS = 120
DEFAULT_PRICE_MONITOR_ALERT_COOLDOWN_SECONDS = 60
DEFAULT_PRICE_MONITOR_ENABLE_PRICE_ALERTS = True
DEFAULT_PRICE_MONITOR_WS_RECONNECT_MIN_SECONDS = 1.0
DEFAULT_PRICE_MONITOR_WS_RECONNECT_MAX_SECONDS = 60.0
DEFAULT_PRICE_MONITOR_NO_EVENT_TIMEOUT_SECONDS = 30

DEFAULT_DAILY_KLINE_INTEGRITY_ENABLED = True
DEFAULT_DAILY_KLINE_INTEGRITY_SYMBOL = "BTCUSDT"
DEFAULT_DAILY_KLINE_INTEGRITY_INTERVAL = "4h"
DEFAULT_DAILY_KLINE_INTEGRITY_LIMIT = 100
DEFAULT_DAILY_KLINE_INTEGRITY_NOTIFY_SUCCESS = True
DEFAULT_DAILY_KLINE_INTEGRITY_LOCK_TTL_SECONDS = 1800
DEFAULT_DAILY_KLINE_INTEGRITY_SCHEDULE_HOUR_UTC = 0
DEFAULT_DAILY_KLINE_INTEGRITY_SCHEDULE_MINUTE_UTC = 15

DEFAULT_HERMES_TIMEOUT_SECONDS = 10.0
DEFAULT_HERMES_MAX_RETRIES = 2
DEFAULT_HERMES_ENABLED = False
DEFAULT_HERMES_DRY_RUN = True

LOG_DIR_NAME = "logs"
DEFAULT_LOG_FILE_NAME = "app.log"

SENSITIVE_FIELD_NAMES = frozenset(
    {
        "mysql_password",
        "redis_password",
        "hermes_webhook_url",
        "hermes_secret",
    }
)

SENSITIVE_TEXT_MARKERS = (
    "password",
    "secret",
    "token",
    "webhook",
    "authorization",
    "cookie",
)

